service: coresident-off-days
frameworkVersion: "3"

 # with useDotenv: true, serverless loads your variables from the `.env` file and puts them in the
 # `env` variable so you can access them using `env:<name>`
useDotenv: true

provider:
  name: aws
  region: us-east-1
  runtime: nodejs16.x
  profile: off-days-tracker
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - dynamodb:*
          Resource: "*"
  environment:
    TABLE_BLOCKS: Blocks
    TABLE_SCHEDULES: Schedules
    TABLE_TEMPLATES: Templates
    TABLE_TEMPLATES_WBG: WeinbergTemplates
    TABLE_SERVICE_REGEX: ServiceRegex
    BOUND_MIN_DATE: 2023-03-02T00:00:00Z
    BOUND_MAX_DATE: 2023-06-30T23:59:59Z
    FORMAT_DATE: YYYY-MM-DD
    POSITION_OFF: OFF
    MAYBE_OFF_SERVICES: Other
    EXP_PLACEHOLDER_POSITION: ":position"
    DEFAULT_PIN: ${env:DEFAULT_PIN}

functions:
  api:
    handler: index.handler
    events:
      - httpApi: "*"

plugins:
  - serverless-offline
